// Sample product data
export const categories = ["FACE", "HAIR", "MAKEUP", "BODY", "BABY", "COMBOS", "NEW LAUNCHES", "BEST SELLERS"]

// Helper function to create URL-friendly slugs from product names
export const createSlug = (name) => {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
}

export const products = [
  {
    id: 1,
    name: "Natural Face Cleanser",
    slug: "natural-face-cleanser",
    description:
      "A gentle, natural face cleanser that removes impurities without stripping your skin of its natural oils.",
    price: 499,
    originalPrice: 699,
    rating: 4.5,
    stock: 25,
    sku: "FC-001",
    category: "FACE",
    image: "https://images.rawpixel.com/image_social_landscape/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvNTAyLWZ4LTQxXzIuanBn.jpg?s=IuRm1waLbzE7OAJ88FbyVNDnF_aZ2p69xuN_MkIOISg",
    images: ["https://images.rawpixel.com/image_social_landscape/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvNTAyLWZ4LTQxXzIuanBn.jpg?s=IuRm1waLbzE7OAJ88FbyVNDnF_aZ2p69xuN_MkIOISg", "https://mashmoshem.co.id/wp-content/uploads/2021/05/body-care-product-1-scaled.jpg", "https://img.freepik.com/premium-photo/set-body-care-products-isolated-white_392895-260105.jpg", "https://img.freepik.com/premium-vector/body-face-cosmetic-product-abstract-design-stand-with-plant-white-background-3d-illustration_281653-9108.jpg"],
    features: [
      "Made with 100% natural ingredients",
      "Suitable for all skin types",
      "Removes makeup and impurities",
      "Hydrates and nourishes skin",
      "Cruelty-free and vegan",
    ],
    specifications: {
      Weight: "150ml",
      Ingredients: "Aloe Vera, Cucumber Extract, Glycerin, Rose Water",
      "Skin Type": "All Skin Types",
      Usage: "Morning and Evening",
      "Shelf Life": "12 months",
    },
  },
  {
    id: 2,
    name: "Hydrating Hair Mask",
    slug: "hydrating-hair-mask",
    description: "Deep conditioning hair mask that repairs damaged hair and adds shine and softness.",
    price: 599,
    originalPrice: 799,
    rating: 4.7,
    stock: 15,
    sku: "HM-002",
    category: "HAIR",
    image: "https://mashmoshem.co.id/wp-content/uploads/2021/05/body-care-product-1-scaled.jpg",
    images: ["https://mashmoshem.co.id/wp-content/uploads/2021/05/body-care-product-1-scaled.jpg"],
    features: [
      "Deep conditioning formula",
      "Repairs split ends",
      "Adds shine and softness",
      "Reduces frizz",
      "Suitable for all hair types",
    ],
    specifications: {
      Weight: "200ml",
      Ingredients: "Argan Oil, Shea Butter, Keratin, Vitamin E",
      "Hair Type": "All Hair Types",
      Usage: "Once a week",
      "Shelf Life": "18 months",
    },
  },
  {
    id: 3,
    name: "Organic Body Lotion",
    slug: "organic-body-lotion",
    description: "Luxurious body lotion that hydrates and nourishes your skin, leaving it soft and smooth.",
    price: 399,
    originalPrice: 599,
    rating: 4.3,
    stock: 30,
    sku: "BL-003",
    category: "BODY",
    image: "https://img.freepik.com/premium-photo/set-body-care-products-isolated-white_392895-260105.jpg",
    images: ["https://img.freepik.com/premium-photo/set-body-care-products-isolated-white_392895-260105.jpg"],
    features: [
      "Deeply moisturizing",
      "Non-greasy formula",
      "Quick absorption",
      "Long-lasting hydration",
      "Subtle natural fragrance",
    ],
    specifications: {
      Weight: "250ml",
      Ingredients: "Coconut Oil, Shea Butter, Almond Oil, Vitamin E",
      "Skin Type": "All Skin Types",
      Usage: "Daily after shower",
      "Shelf Life": "24 months",
    },
  },
  {
    id: 4,
    name: "Natural Lip Balm Set",
    slug: "natural-lip-balm-set",
    description: "Set of 4 natural lip balms in different flavors to keep your lips moisturized and protected.",
    price: 299,
    originalPrice: 399,
    rating: 4.8,
    stock: 50,
    sku: "LB-004",
    category: "MAKEUP",
    image: "https://img.freepik.com/premium-vector/body-face-cosmetic-product-abstract-design-stand-with-plant-white-background-3d-illustration_281653-9108.jpg",
    images: ["https://img.freepik.com/premium-vector/body-face-cosmetic-product-abstract-design-stand-with-plant-white-background-3d-illustration_281653-9108.jpg"],
    features: [
      "100% natural ingredients",
      "Long-lasting moisture",
      "Protects lips from drying",
      "Available in 4 flavors",
      "Pocket-sized for on-the-go",
    ],
    specifications: {
      Weight: "4 x 5g",
      Ingredients: "Beeswax, Coconut Oil, Shea Butter, Natural Flavors",
      Flavors: "Strawberry, Mint, Vanilla, Coconut",
      Usage: "Apply as needed",
      "Shelf Life": "18 months",
    },
  },
  {
    id: 5,
    name: "Baby Care Gift Set",
    slug: "baby-care-gift-set",
    description: "Complete baby care set with gentle products specially formulated for baby's delicate skin.",
    price: 999,
    originalPrice: 1299,
    rating: 4.9,
    stock: 10,
    sku: "BC-005",
    category: "BABY",
    image: "https://img.freepik.com/premium-photo/set-body-care-products-isolated-white_392895-260105.jpg",
    images: ["https://img.freepik.com/premium-photo/set-body-care-products-isolated-white_392895-260105.jpg"],
    features: [
      "Gentle and safe for babies",
      "Hypoallergenic formula",
      "No harsh chemicals",
      "Dermatologically tested",
      "Perfect gift for new parents",
    ],
    specifications: {
      Contents: "Baby Shampoo, Baby Lotion, Baby Oil, Baby Powder, Baby Soap",
      Ingredients: "Aloe Vera, Chamomile, Calendula, Natural Oils",
      "Age Range": "0-24 months",
      Usage: "As needed for baby care",
      "Shelf Life": "24 months",
    },
  },
  {
    id: 6,
    name: "Aromatherapy Diffuser",
    slug: "aromatherapy-diffuser",
    description: "Elegant ceramic diffuser that fills your home with natural essential oil fragrances.",
    price: 1499,
    originalPrice: 1999,
    rating: 4.6,
    stock: 8,
    sku: "AD-006",
    category: "COMBOS",
    image: "https://mashmoshem.co.id/wp-content/uploads/2021/05/body-care-product-1-scaled.jpg",
    images: ["https://mashmoshem.co.id/wp-content/uploads/2021/05/body-care-product-1-scaled.jpg"],
    features: [
      "Elegant ceramic design",
      "LED mood lighting",
      "Ultrasonic technology",
      "Auto shut-off feature",
      "Whisper-quiet operation",
    ],
    specifications: {
      Size: "15cm x 15cm x 12cm",
      Capacity: "300ml",
      "Run Time": "Up to 8 hours",
      Coverage: "Up to 400 sq ft",
      Warranty: "1 year",
    },
  },
  {
    id: 7,
    name: "New Launch Face Serum",
    slug: "new-launch-face-serum",
    description: "Revolutionary face serum with advanced anti-aging properties for youthful, radiant skin.",
    price: 1299,
    originalPrice: 1599,
    rating: 4.8,
    stock: 20,
    sku: "FS-007",
    category: "NEW LAUNCHES",
    image: "https://images.rawpixel.com/image_social_landscape/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvNTAyLWZ4LTQxXzIuanBn.jpg?s=IuRm1waLbzE7OAJ88FbyVNDnF_aZ2p69xuN_MkIOISg",
    images: ["https://images.rawpixel.com/image_social_landscape/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvNTAyLWZ4LTQxXzIuanBn.jpg?s=IuRm1waLbzE7OAJ88FbyVNDnF_aZ2p69xuN_MkIOISg"],
    features: [
      "Advanced anti-aging formula",
      "Reduces fine lines and wrinkles",
      "Brightens and evens skin tone",
      "Hydrates and plumps skin",
      "Suitable for all skin types",
    ],
    specifications: {
      Weight: "30ml",
      Ingredients: "Hyaluronic Acid, Vitamin C, Peptides, Niacinamide",
      Usage: "Apply daily after cleansing",
      "Shelf Life": "12 months",
    },
  }
]
